language: python
python:
  - "3.5"
  - "3.6"
services:
  - redis-server

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

# command to run tests
script: pytest --cov-report=xml --cov=aiotasks/ tests/

after_success:
  - codecov

os:
  - linux

cache:
  directories:
  - $HOME/.cache/pip