language: python
sudo: false

python:
  - "3.5"
#  - "3.6"

#services:
#  - redis-server

# command to install dependencies
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade setuptools
  - pip install tox-travis

script:
  # Only run tests if there's changes in python code
  - CHANGES=$(git diff --name-only  aiotasks/)
  - if [[ $CHANGES != "" ]]; then tox; fi

after_success:
  - pip install codecov
  - codecov

os:
  - linux

cache:
  directories:
  - $HOME/.cache/pip

deploy:

  # Deploy to PyPI
  - provider: script
    user: $PYPI_USER
    password: $PYPI_PASSWD
    distributions: "sdist"
    on:
      branch: master
      tags: true
      condition: "CHANGES=$(git diff --name-only  aiotasks/) && if [[ $CHANGES != '' ]]; then tox; fi"

  #- provider: releases
  #  api_key: $GITHUB_AUTH
  #  file: dist/*.tar.gz
  #  file_glob: true
  #  skip_cleanup: true
  #  on:
  #    tags: true